((nil . ((cider-preferred-build-tool . clojure-cli)
         ;; (cider-default-cljs-repl . figwheel-main)
	 ;; (cider-clojure-cli-global-options . "-R:dev")
	 ;; (cider-figwheel-main-default-options . ":fig")
	 )))
