version: 2.1

# Default settings for executors

defaults: &defaults
  working_directory: ~/repo

env_defaults: &env_defaults
  LEIN_ROOT: "true"   # we intended to run lein as root
  # JVM_OPTS:
  # - limit the maximum heap size to prevent out of memory errors
  # - print stacktraces to console
  JVM_OPTS: >
    -Xmx3200m
    -Dclojure.main.report=stderr

# Runners for OpenJDK 8/11/16

executors:
  # JDK 8 is preferred for deployments (https://github.com/benedekfazekas/mranderson/issues/57)
  # Parallelism is disabled, at least for now (https://github.com/benedekfazekas/mranderson/issues/56)
  openjdk8_deploy:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node
    <<: *defaults
    environment:
      LEIN_JVM_OPTS: -Dmranderson.internal.no-parallelism=true
      <<: *env_defaults
  openjdk8:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node
    environment:
      <<: *env_defaults
    <<: *defaults
  openjdk11:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1-node
    environment:
      <<: *env_defaults
    <<: *defaults
  openjdk16:
    docker:
      - image: circleci/clojure:openjdk-16-lein-2.9.5-buster-node
    environment:
      <<: *env_defaults
    <<: *defaults
  openjdk17:
    docker:
      - image: circleci/clojure:openjdk-17-lein-2.9.5-buster-node
    <<: *defaults
    environment:
      <<: *env_defaults

commands:
  with_cache:
    description: |
      Run a set of steps with Maven dependencies and Clojure classpath cache
      files cached.
      This command restores ~/.m2 and .cpcache if they were previously cached,
      then runs the provided steps, and finally saves the cache.
      The cache-key is generated based on the contents of `deps.edn` present in
      the `working_directory`.
    parameters:
      steps:
        type: steps
      files:
        description: Files to consider when creating the cache key
        type: string
        default: "deps.edn project.clj build.boot"
      cache_version:
        type: string
        description: "Change this value to force a cache update"
        default: "1"
    steps:
      - run:
          name: Install Clojure
          command: |
            wget -nc https://download.clojure.org/install/linux-install-1.10.3.855.sh
            chmod +x linux-install-1.10.3.855.sh
            sudo ./linux-install-1.10.3.855.sh
      - run:
          name: Install make
          command: |
            sudo apt-get install make
      - run:
          name: Generate Cache Checksum
          command: |
            for file in << parameters.files >>
            do
              find . -name $file -exec cat {} +
            done | shasum | awk '{print $1}' > /tmp/clojure_cache_seed
      - restore_cache:
          key: clojure-<< parameters.cache_version >>-{{ checksum "/tmp/clojure_cache_seed" }}
      - steps: << parameters.steps >>
      - save_cache:
          paths:
            - ~/.m2
            - .cpcache
          key: clojure-<< parameters.cache_version >>-{{ checksum "/tmp/clojure_cache_seed" }}

jobs:

  util_job:
    description: |
      Running utility commands/checks (linter etc.)
      Always uses Java11 and Clojure 1.10
    parameters:
      steps:
        type: steps
    executor: openjdk11
    environment:
      VERSION: "1.10"
    steps:
      - checkout
      - with_cache:
          cache_version: "1.10"
          steps: << parameters.steps >>

  deploy:
    executor: openjdk8_deploy
    steps:
      - checkout
      - run:
         name: Deploy
         command: |
           lein with-profile -user,+deploy run -m deploy-release make deploy

  test_code:
    description: |
      Run tests against given version of JDK and Clojure
    parameters:
      jdk_version:
        description: Version of JDK to test against
        type: string
      clojure_version:
        description: Version of Clojure to test against
        type: string
    executor: << parameters.jdk_version >>
    environment:
      VERSION: << parameters.clojure_version >>
    steps:
      - checkout
      - with_cache:
          cache_version: << parameters.clojure_version >>|<< parameters.jdk_version >>
          steps:
            - run:
                name: Ensure node.js
                command: node --version
            - run:
                name: Running tests
                command: make test

workflows:
  version: 2.1
  ci-test-matrix:
    jobs:
      - test_code:
          matrix:
            parameters:
              # FIXME other things worth adding to the matrix:
              # - cider-nrepl
              # - node.js runtimes
              clojure_version: ["1.8", "1.9", "1.10", "1.11", "master"]
              jdk_version: [openjdk8, openjdk11, openjdk16, openjdk17]
      - util_job:
          name: Code Linting
          steps:
            - run:
                name: Running clj-kondo
                command: |
                  make kondo
            - run:
                name: Running Eastwood
                command: |
                  make eastwood
      - deploy:
          requires:
            - test_code
            - "Code Linting"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d*)?(-beta\d*)?$/
